### ISSUE TITLE
The models would be evaluated as incoherent.

### ISSUE THREAD

**Issue by apoplexyes** [impel-intelligence/dippy-bittensor-subnet#76]
I found an issue that consequence models would be evaluated as incoherent.
There are 2 cases.
- API call for gathering dataset for evaluation of coherent. (Due to security issue, stop api call & empty dataset return.)
- OPENAI api key expired.

![image](https://github.com/user-attachments/assets/0e3a7443-2d61-4ea6-a157-e9440b8aee61)

These are sample examples of what I am saying.

Thanks

**Comment by donaldknoller** [comment]
Can you please provide specific details on why this would differ from https://github.com/impel-intelligence/dippy-bittensor-subnet/issues/73 ?
Also there is no direct proof of these claims:

OPENAI api key expired -> if this were the case, all coherence evaluations would be failing
API call for gathering dataset for evaluation of coherent. (Due to security issue, stop api call & empty dataset return.) -> please provide a specific code solution if this is the case, otherwise we can address this as part of https://github.com/impel-intelligence/dippy-bittensor-subnet/issues/64 . I have updated the title to better reflect the root cause

**Comment by torquedrop** [comment]
![image](https://github.com/user-attachments/assets/ca5ad92d-fdd6-4e4c-b6da-f72b6de6be87)
I don't think it's because of openai api key or API call expiration.
As you can see on above image, if the models are submitted at once in a very short time, the validators would be glitched.
In that case, there's probability to pass the models' evaluation.

**Comment by apoplexyes** [comment]
![image](https://github.com/user-attachments/assets/3fc9a175-e39b-48e9-b751-f894ea23a900)
It could be.
I found another possibility.
What if the validators' openai request exceeds limit?
In that case, it's truely possible to get 0 coherent score.

**Comment by donaldknoller** [comment]
Some clarification:
1. I believe there is some confusion regarding receiving a _real_ coherence score of 0 vs what _appears_ to be a coherence score of 0. In the code, there is a minimum threshold of 0.95. Any coherence score that falls below (ie. 0.9444....) would be marked down to 0
2. Given the above, the _real_ core issue here is not a specific error in the API (which is monitored), but rather the specific _variance_ of the score.

**Comment by donaldknoller** [comment]
Addressed via this issue: https://github.com/impel-intelligence/dippy-bittensor-subnet/issues/64
There have been no erroneous incoherent model errors in the past 24 hours of scoring since the change was applied.
